[window]
padding.x = 15
padding.y = 15

opacity = 0.95

[font]
size = 14.0

[font.bold]
family = "InconsolataNerdFont"
style = "Bold"

[font.italic]
family = "InconsolataNerdFont"
style = "Italic"

[font.bold_italic]
family = "InconsolataNerdFont"
style = "Bold Italic"

[font.normal]
family = "InconsolataNerdFont"
style = "Regular"

[colors.primary]
background = "#272E33"
foreground = "#D3C6AA"

[colors.normal]
black   = "#1E2326"
red     = "#E67E80"
green   = "#A7C080"
yellow  = "#DBBC7F"
blue    = "#7FBBB3"
magenta = "#D699B6"
cyan    = "#83C092"
white   = "#F2EFDF"

[colors.bright]
black   = "#293136"
red     = "#F85552"
green   = "#8DA101"
yellow  = "#DFA000"
blue    = "#3A94C5"
magenta = "#DF69BA"
cyan    = "#35A77C"
white   = "#FFFBEF"
